{"timestamp":"2025-09-27T13:13:52.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:00.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:05.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:09.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:12.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:20.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:24.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:27.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:31.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:35.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:39.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:45.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:14:49.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:14:58.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:15:02.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:15:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:15:21.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"ERROR","message":"Системная ошибка приложения","event":{"code":"010105","name":"SYSTEM.APP.ERROR","message":"Ошибка запуска приложения"},"extra":{"error":{"name":"gaierror","value":"[Errno -2] Name or service not known"},"traceback":"Traceback (most recent call last):\n  File \"/app/lifespan.py\", line 17, in lifespan\n    await init_db()\n  File \"/app/adapters/db/init_db.py\", line 84, in init_db\n    await init_models()\n  File \"/app/adapters/db/init_db.py\", line 66, in init_models\n    async with engine.begin() as conn:\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 210, in __aenter__\n    return await anext(self.gen)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 1066, in begin\n    async with conn:\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/base.py\", line 121, in __aenter__\n    return await self.start(is_ctxmanager=True)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/engine.py\", line 274, in start\n    await greenlet_spawn(self.sync_engine.connect)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3273, in connect\n    return self._connection_cls(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 145, in __init__\n    self._dbapi_connection = engine.raw_connection()\n                             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 3297, in raw_connection\n    return self.pool.connect()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 449, in connect\n    return _ConnectionFairy._checkout(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 1264, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 713, in checkout\n    rec = pool._do_get()\n          ^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 179, in _do_get\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py\", line 177, in _do_get\n    return self._create_connection()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 390, in _create_connection\n    return _ConnectionRecord(self)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 675, in __init__\n    self.__connect()\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 901, in __connect\n    with util.safe_reraise():\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py\", line 224, in __exit__\n    raise exc_value.with_traceback(exc_tb)\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/pool/base.py\", line 897, in __connect\n    self.dbapi_connection = connection = pool._invoke_creator(self)\n                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py\", line 646, in connect\n    return dialect.connect(*cargs, **cparams)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 625, in connect\n    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 961, in connect\n    await_only(creator_fn(*arg, **kw)),\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n            ^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connection.py\", line 2421, in connect\n    return await connect_utils._connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1075, in _connect\n    raise last_error or exceptions.TargetServerAttributeNotMatched(\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 1049, in _connect\n    conn = await _connect_addr(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 886, in _connect_addr\n    return await __connect_addr(params, True, *args)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 931, in __connect_addr\n    tr, pr = await connector\n             ^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/asyncpg/connect_utils.py\", line 802, in _create_ssl_connection\n    tr, pr = await loop.create_connection(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1046, in create_connection\n    infos = await self._ensure_resolved(\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 1420, in _ensure_resolved\n    return await loop.getaddrinfo(host, port, family=family, type=type,\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 868, in getaddrinfo\n    return await self.run_in_executor(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/socket.py\", line 974, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsocket.gaierror: [Errno -2] Name or service not known\n","request_id":null}}
{"timestamp":"2025-09-27T13:15:49.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Запуск приложения","event":{"code":"010101","name":"SYSTEM.APP.STARTUP","message":"Запуск приложения"},"extra":{"request_id":null}}
{"timestamp":"2025-09-27T13:17:05.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"POST","url":"http://localhost:8000/api/v1/auth/access-token","headers":{"host":"localhost:8000","connection":"keep-alive","content-length":"29","sec-ch-ua-platform":"\"Windows\"","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-ch-ua":"\"Chromium\";v=\"140\", \"Not=A?Brand\";v=\"24\", \"Google Chrome\";v=\"140\"","content-type":"application/x-www-form-urlencoded","sec-ch-ua-mobile":"?0","accept":"*/*","origin":"http://localhost:3000","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"username=admin&password=admin","request_id":"b05914e0570920fd"}}
{"timestamp":"2025-09-27T13:17:05.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"content-length":"271","content-type":"application/json","set-cookie":"refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjE1NzEwMjUsInN1YiI6IjEifQ.zkpr0Kox1hYpmNRk4xd9sg8bIprt8JSjwqOmFe0WHP4; Path=/; SameSite=lax","access-control-allow-origin":"*","access-control-allow-credentials":"true","x-request-id":"b05914e0570920fd"},"body":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk4NDMwMjUsInN1YiI6IjEifQ.Fz3DCsCKpD2pCYR_2tWeaVYQP-wpByxQKd9O4ftCk-I","token_type":"bearer","user":{"id":1,"login":"admin","name":"Admin","is_active":true,"is_superuser":true},"ts":"2025-09-27 13:17:05"},"processing_time_ms":247.32,"request_id":"b05914e0570920fd"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"POST","url":"http://localhost:8000/api/v1/auth/access-token","headers":{"host":"localhost:8000","connection":"keep-alive","content-length":"29","sec-ch-ua-platform":"\"Windows\"","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-ch-ua":"\"Chromium\";v=\"140\", \"Not=A?Brand\";v=\"24\", \"Google Chrome\";v=\"140\"","content-type":"application/x-www-form-urlencoded","sec-ch-ua-mobile":"?0","accept":"*/*","origin":"http://localhost:3000","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"username=admin&password=admin","request_id":"8a5e00676ec3f4f7"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"content-length":"271","content-type":"application/json","set-cookie":"refresh-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NjE1NzEwMzYsInN1YiI6IjEifQ.FZjUcxbSmom0XWtHKuNxKJnnlJ04_h7sCvbbo3sRnkk; Path=/; SameSite=lax","access-control-allow-origin":"*","access-control-allow-credentials":"true","x-request-id":"8a5e00676ec3f4f7"},"body":{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk4NDMwMzYsInN1YiI6IjEifQ.J7sOohEI9Yb4M26IMMtzA7qg0oyzqFUWZKmhT_L0d2g","token_type":"bearer","user":{"id":1,"login":"admin","name":"Admin","is_active":true,"is_superuser":true},"ts":"2025-09-27 13:17:16"},"processing_time_ms":233.41,"request_id":"8a5e00676ec3f4f7"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"OPTIONS","url":"http://localhost:8000/api/v1/auth/test-token","headers":{"host":"localhost:8000","connection":"keep-alive","accept":"*/*","access-control-request-method":"POST","access-control-request-headers":"authorization","origin":"http://localhost:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-fetch-mode":"cors","sec-fetch-site":"same-site","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"5e2c4c344b40a405"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"vary":"Origin","access-control-allow-methods":"DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT","access-control-max-age":"600","access-control-allow-credentials":"true","access-control-allow-origin":"http://localhost:3000","access-control-allow-headers":"authorization","content-length":"2","content-type":"text/plain; charset=utf-8","x-request-id":"5e2c4c344b40a405"},"body":"OK","processing_time_ms":2.5,"request_id":"5e2c4c344b40a405"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"POST","url":"http://localhost:8000/api/v1/auth/test-token","headers":{"host":"localhost:8000","connection":"keep-alive","content-length":"0","sec-ch-ua-platform":"\"Windows\"","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk4NDMwMzYsInN1YiI6IjEifQ.J7sOohEI9Yb4M26IMMtzA7qg0oyzqFUWZKmhT_L0d2g","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-ch-ua":"\"Chromium\";v=\"140\", \"Not=A?Brand\";v=\"24\", \"Google Chrome\";v=\"140\"","sec-ch-ua-mobile":"?0","accept":"*/*","origin":"http://localhost:3000","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"b6da25437fd1c957"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"OPTIONS","url":"http://localhost:8000/api/v1/auth/test-token","headers":{"host":"localhost:8000","connection":"keep-alive","accept":"*/*","access-control-request-method":"POST","access-control-request-headers":"authorization","origin":"http://localhost:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-fetch-mode":"cors","sec-fetch-site":"same-site","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"48ca95f84400744c"}}
{"timestamp":"2025-09-27T13:17:16.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"vary":"Origin","access-control-allow-methods":"DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT","access-control-max-age":"600","access-control-allow-credentials":"true","access-control-allow-origin":"http://localhost:3000","access-control-allow-headers":"authorization","content-length":"2","content-type":"text/plain; charset=utf-8","x-request-id":"48ca95f84400744c"},"body":"OK","processing_time_ms":1.09,"request_id":"48ca95f84400744c"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"POST","url":"http://localhost:8000/api/v1/auth/test-token","headers":{"host":"localhost:8000","connection":"keep-alive","content-length":"0","sec-ch-ua-platform":"\"Windows\"","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk4NDMwMzYsInN1YiI6IjEifQ.J7sOohEI9Yb4M26IMMtzA7qg0oyzqFUWZKmhT_L0d2g","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-ch-ua":"\"Chromium\";v=\"140\", \"Not=A?Brand\";v=\"24\", \"Google Chrome\";v=\"140\"","sec-ch-ua-mobile":"?0","accept":"*/*","origin":"http://localhost:3000","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"309bf0377ae77bfb"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"content-length":"172","content-type":"application/json","access-control-allow-origin":"*","access-control-allow-credentials":"true","x-request-id":"b6da25437fd1c957"},"body":{"user":{"name":"Admin","login":"admin","ext_api_key":"pv8NdHGU8ZfVJ-E2nHlMz1vLu_GguzXWApbWGaLzxug","is_active":true,"is_superuser":true,"id":1},"ts":"2025-09-27T13:17:17"},"processing_time_ms":20.3,"request_id":"b6da25437fd1c957"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"content-length":"172","content-type":"application/json","access-control-allow-origin":"*","access-control-allow-credentials":"true","x-request-id":"309bf0377ae77bfb"},"body":{"user":{"name":"Admin","login":"admin","ext_api_key":"pv8NdHGU8ZfVJ-E2nHlMz1vLu_GguzXWApbWGaLzxug","is_active":true,"is_superuser":true,"id":1},"ts":"2025-09-27T13:17:17"},"processing_time_ms":7.76,"request_id":"309bf0377ae77bfb"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"OPTIONS","url":"http://localhost:8000/api/v1/accounts/","headers":{"host":"localhost:8000","connection":"keep-alive","accept":"*/*","access-control-request-method":"GET","access-control-request-headers":"authorization","origin":"http://localhost:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-fetch-mode":"cors","sec-fetch-site":"same-site","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"53069a5e17bc1773"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"OPTIONS","url":"http://localhost:8000/api/v1/accounts/","headers":{"host":"localhost:8000","connection":"keep-alive","accept":"*/*","access-control-request-method":"GET","access-control-request-headers":"authorization","origin":"http://localhost:3000","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-fetch-mode":"cors","sec-fetch-site":"same-site","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"8689bd0d5eebd697"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"vary":"Origin","access-control-allow-methods":"DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT","access-control-max-age":"600","access-control-allow-credentials":"true","access-control-allow-origin":"http://localhost:3000","access-control-allow-headers":"authorization","content-length":"2","content-type":"text/plain; charset=utf-8","x-request-id":"53069a5e17bc1773"},"body":"OK","processing_time_ms":3.16,"request_id":"53069a5e17bc1773"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"vary":"Origin","access-control-allow-methods":"DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT","access-control-max-age":"600","access-control-allow-credentials":"true","access-control-allow-origin":"http://localhost:3000","access-control-allow-headers":"authorization","content-length":"2","content-type":"text/plain; charset=utf-8","x-request-id":"8689bd0d5eebd697"},"body":"OK","processing_time_ms":3.13,"request_id":"8689bd0d5eebd697"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"GET","url":"http://localhost:8000/api/v1/accounts/","headers":{"host":"localhost:8000","connection":"keep-alive","sec-ch-ua-platform":"\"Windows\"","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk4NDMwMzYsInN1YiI6IjEifQ.J7sOohEI9Yb4M26IMMtzA7qg0oyzqFUWZKmhT_L0d2g","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-ch-ua":"\"Chromium\";v=\"140\", \"Not=A?Brand\";v=\"24\", \"Google Chrome\";v=\"140\"","sec-ch-ua-mobile":"?0","accept":"*/*","origin":"http://localhost:3000","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"fb339413be9f8218"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"content-length":"21","content-type":"application/json","access-control-allow-origin":"*","access-control-allow-credentials":"true","x-request-id":"fb339413be9f8218"},"body":{"data":[],"total":0},"processing_time_ms":23.89,"request_id":"fb339413be9f8218"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Получен входящий запрос","event":{"code":"010301","name":"SYSTEM.API.REQUEST","message":"Получен входящий запрос"},"extra":{"client_ip":"172.18.0.1","method":"GET","url":"http://localhost:8000/api/v1/accounts/","headers":{"host":"localhost:8000","connection":"keep-alive","sec-ch-ua-platform":"\"Windows\"","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTk4NDMwMzYsInN1YiI6IjEifQ.J7sOohEI9Yb4M26IMMtzA7qg0oyzqFUWZKmhT_L0d2g","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36","sec-ch-ua":"\"Chromium\";v=\"140\", \"Not=A?Brand\";v=\"24\", \"Google Chrome\";v=\"140\"","sec-ch-ua-mobile":"?0","accept":"*/*","origin":"http://localhost:3000","sec-fetch-site":"same-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"http://localhost:3000/","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"},"query_params":{},"body":"","request_id":"0706f2a28311aec9"}}
{"timestamp":"2025-09-27T13:17:17.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Успешный ответ (HTTP 2xx)","event":{"code":"010302","name":"SYSTEM.API.RESPONSE","message":"Успешный ответ (HTTP 2xx)"},"extra":{"status_code":200,"headers":{"content-length":"21","content-type":"application/json","access-control-allow-origin":"*","access-control-allow-credentials":"true","x-request-id":"0706f2a28311aec9"},"body":{"data":[],"total":0},"processing_time_ms":10.98,"request_id":"0706f2a28311aec9"}}
{"timestamp":"2025-09-27T13:18:42.%fZ","service":{"name":"FastAPI","version":"0.0.1","env":"dev","instance_id":null,"host":"2fa42e3e1307"},"name":"cloud_access_point","level":"INFO","message":"Остановка приложения","event":{"code":"010102","name":"SYSTEM.APP.SHUTDOWN","message":"Остановка приложения"},"extra":{"request_id":null}}
